Create new-doc.md
WordPress/Documentation-Issue-Tracker pull request #28
Opened 2021-09-02 21:44 UTC by femkreations

Initial version of the new doc template

2021-09-03 21:25 UTC, zzap reviewed
Are we going to have labels for these issues?

2021-09-08 10:17 UTC, zzap requested changes

2021-09-08 10:17 UTC, zzap commented on .github/ISSUE_TEMPLATE/new-doc.md
> +
We have `new document` label now so you can add it here. Thanks

2021-09-13 20:36 UTC, theMikeD commented
`Please describe the new page that you are requesting.` seems a little more straightforward.

2021-09-14 14:10 UTC, femkreations reviewed
Updating the description in the first field

2021-09-21 14:21 UTC, zzap approved these changes

2021-09-21 14:21 UTC, merged